name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: compile
     run: gcc test_calculadora.c -o test_calculadora
    - name: execute
     run: ./test_calculadora
    - name: compile programa principal
     run: gcc calculadora-3.c -o calculadora-3
    - name: execute programa principal
     run: ./calculadora 1 3 4

